### PR TITLE
Fix: Address GolangCI lint 1.55 errors

### PR DESCRIPTION
**Pull request by dhiguero**
### Description of your changes

In preparation for updating the underlying golang version, this PR address the errors reported by GolangCI 1.55 which works with golang 1.21

A summary of the types of errors reported are:

* Unused parameters (revive)
* ineffectual assignment to err (ineffassign)
* Implicit memory aliasing in for loop. (gosec)
* redefinition of the built-in function new (revive)
* XYZ has 5 occurrences, make it a constant (goconst)
* if block ends with a continue statement, so drop this else and outdent its block (revive)
* response body must be closed (bodyclose)
* non-wrapping format verb for fmt.Errorf. Use `%w` to format errors (errorlint)

<details>
   <summary>Full output of golang lint 1.55.2 with current file</summary>

```bash
$ GOLANGCILINT_VERSION=1.55.2 make lint                                                                                                                                                                       
13:18:29 [ OK ] golangci-lint is already installed
13:18:29 [INFO] lint
INFO [config_reader] Config search paths: [./ /Users/dhiguero/development/dhiguero/kubevela /Users/dhiguero/development/dhiguero /Users/dhiguero/development /Users/dhiguero /Users /]
INFO [config_reader] Used config file .golangci.yml
INFO [lintersdb] Active 37 linters: [asasalint asciicheck bidichk bodyclose durationcheck errcheck errorlint exhaustive exportloopref gocheckcompilerdirectives gochecksumtype goconst gocritic gocyclo gofmt goimports gosec gosimple gosmopolitan govet ineffassign loggercheck makezero misspell musttag nakedret nilerr noctx protogetter reassign revive staticcheck testifylint unconvert unparam unused zerologlint]
INFO [lintersdb] Active presets: [bugs unused]
INFO [loader] Go packages loading at mode 575 (types_sizes|compiled_files|exports_file|imports|name|deps|files) took 1.302387958s
INFO [runner/filename_unadjuster] Pre-built 0 adjustments in 32.895541ms
INFO [linters_context/goanalysis] analyzers took 0s with no stages
INFO [runner] fixer took 0s with no stages
INFO [runner/skip_dirs] Skipped 16 issues from dir e2e by pattern e2e
INFO [runner/skip_dirs] Skipped 2 issues from dir pkg/builtin/registry by pattern (^|/)builtin($|/)
INFO [runner/skip_dirs] Skipped 5 issues from dir pkg/builtin/http by pattern (^|/)builtin($|/)
INFO [runner/skip_dirs] Skipped 1 issues from dir e2e/addon/mock/utils by pattern e2e
INFO [runner/skip_dirs] Skipped 30 issues from dir e2e/addon/mock by pattern e2e
INFO [runner/skip_dirs] Skipped 3 issues from dir hack/docgen/def/collect-translation by pattern hack
INFO [runner/skip_dirs] Skipped 1 issues from dir hack/crd/dispatch by pattern hack
INFO [runner/skip_dirs] Skipped 3 issues from dir pkg/builtin/build by pattern (^|/)builtin($|/)
INFO [runner/skip_dirs] Skipped 10 issues from dir hack/docgen/def/mods by pattern hack
INFO [runner/skip_dirs] Skipped 12 issues from dir hack/docgen/cli by pattern hack
INFO [runner/skip_dirs] Skipped 1 issues from dir pkg/builtin by pattern (^|/)builtin($|/)
INFO [runner/skip_dirs] Skipped 6 issues from dir pkg/builtin/kind by pattern (^|/)builtin($|/)
INFO [runner/skip_dirs] Skipped 1 issues from dir hack/docgen/terraform by pattern hack
INFO [runner/skip_dirs] Skipped 3 issues from dir hack/utils by pattern hack
INFO [runner/skip_dirs] Skipped 1 issues from dir hack/docgen/def by pattern hack
INFO [runner/max_from_linter] 19/69 issues from linter revive were hidden, use --max-issues-per-linter
INFO [runner] Issues before processing: 2732, after processing: 66
INFO [runner] Processors filtering stat (out/in): diff: 85/85, max_from_linter: 66/85, source_code: 66/66, path_shortener: 66/66, path_prettifier: 2732/2732, uniq_by_line: 85/127, max_same_issues: 85/85, severity-rules: 66/66, sort_results: 66/66, cgo: 2732/2732, skip_files: 885/2732, autogenerated_exclude: 790/790, nolint: 127/191, max_per_file_from_linter: 85/85, path_prefixer: 66/66, filename_unadjuster: 2732/2732, identifier_marker: 790/790, exclude: 790/790, exclude-rules: 191/790, fixer: 66/66, skip_dirs: 790/885
INFO [runner] processing took 56.321291ms with stages: nolint: 23.693958ms, path_prettifier: 10.975625ms, identifier_marker: 8.065709ms, exclude-rules: 5.8725ms, autogenerated_exclude: 4.08ms, skip_files: 1.575834ms, skip_dirs: 1.084542ms, source_code: 755.333µs, cgo: 97.834µs, filename_unadjuster: 49.959µs, fixer: 25.041µs, uniq_by_line: 19.499µs, max_from_linter: 9.293µs, path_shortener: 9.291µs, max_same_issues: 4.249µs, max_per_file_from_linter: 1.583µs, exclude: 292ns, sort_results: 249ns, severity-rules: 209ns, diff: 208ns, path_prefixer: 83ns
INFO [runner] linters took 738.841959ms with stages: goanalysis_metalinter: 682.462167ms
pkg/utils/helm/repo_index.go:36:20: unused-parameter: parameter 'ctx' seems to be unused, consider removing or renaming it as _ (revive)
func LoadRepoIndex(ctx context.Context, u string, cred *RepoCredential) (*helmrepo.IndexFile, error) {
                   ^
pkg/workflow/providers/terraform/terraform.go:43:72: unused-parameter: parameter 'wfCtx' seems to be unused, consider removing or renaming it as _ (revive)
func (p *provider) LoadTerraformComponents(ctx monitorContext.Context, wfCtx wfContext.Context, v *value.Value, act wfTypes.Action) error {
                                                                       ^
pkg/workflow/providers/terraform/terraform.go:58:40: unused-parameter: parameter 'ctx' seems to be unused, consider removing or renaming it as _ (revive)
func (p *provider) GetConnectionStatus(ctx monitorContext.Context, wfCtx wfContext.Context, v *value.Value, act wfTypes.Action) error {
                                       ^
references/docgen/console.go:128:134: unused-parameter: parameter 'rev' seems to be unused, consider removing or renaming it as _ (revive)
func (ref *ConsoleReference) Show(ctx context.Context, c common.Args, ioStreams cmdutil.IOStreams, capabilityName string, ns string, rev int64) error {
                                                                                                                                     ^
references/docgen/markdown.go:142:54: unused-parameter: parameter 'ctx' seems to be unused, consider removing or renaming it as _ (revive)
func (ref *MarkdownReference) GenerateMarkdownForCap(ctx context.Context, c types.Capability, pd *packages.PackageDiscover, containSuffix bool) (string, error) {
                                                     ^
pkg/config/provider/provider.go:59:55: unused-parameter: parameter 'wfCtx' seems to be unused, consider removing or renaming it as _ (revive)
func (p *provider) Create(ctx monitorContext.Context, wfCtx wfContext.Context, v *value.Value, act types.Action) error {
                                                      ^
pkg/config/provider/provider.go:87:53: unused-parameter: parameter 'wfCtx' seems to be unused, consider removing or renaming it as _ (revive)
func (p *provider) Read(ctx monitorContext.Context, wfCtx wfContext.Context, v *value.Value, act types.Action) error {
                                                    ^
pkg/config/provider/provider.go:99:53: unused-parameter: parameter 'wfCtx' seems to be unused, consider removing or renaming it as _ (revive)
func (p *provider) List(ctx monitorContext.Context, wfCtx wfContext.Context, v *value.Value, act types.Action) error {
                                                    ^
pkg/config/provider/provider.go:128:55: unused-parameter: parameter 'wfCtx' seems to be unused, consider removing or renaming it as _ (revive)
func (p *provider) Delete(ctx monitorContext.Context, wfCtx wfContext.Context, v *value.Value, act types.Action) error {
                                                      ^
pkg/definition/gen_sdk/gen_sdk.go:465:11: ineffectual assignment to err (ineffassign)
	tmpFile, err := os.CreateTemp("", g.meta.name+"-*.json")
	         ^
pkg/controller/core.oam.dev/v1beta1/application/revision.go:253:38: G601: Implicit memory aliasing in for loop. (gosec)
		hash, err := utils.ComputeSpecHash(&wd.Spec)
		                                   ^
pkg/controller/core.oam.dev/v1beta1/application/revision.go:274:38: G601: Implicit memory aliasing in for loop. (gosec)
		hash, err := utils.ComputeSpecHash(&pd.Spec)
		                                   ^
pkg/controller/core.oam.dev/v1beta1/application/application_controller.go:542:5: redefines-builtin-id: redefinition of the built-in function new (revive)
				new, isNewApp := e.ObjectNew.DeepCopyObject().(*v1beta1.Application)
				^
pkg/controller/core.oam.dev/v1beta1/application/application_controller.go:619:2: redefines-builtin-id: redefinition of the built-in function new (revive)
	new, isNewRT := e.ObjectNew.DeepCopyObject().(*v1beta1.ResourceTracker)
	^
pkg/cmd/utils.go:28:19: unused-parameter: parameter 'f' seems to be unused, consider removing or renaming it as _ (revive)
func GetNamespace(f Factory, cmd *cobra.Command) string {
                  ^
pkg/appfile/appfile.go:206:44: unused-parameter: parameter 'ctx' seems to be unused, consider removing or renaming it as _ (revive)
func (af *Appfile) GeneratePolicyManifests(ctx context.Context) ([]*unstructured.Unstructured, error) {
                                           ^
pkg/webhook/core.oam.dev/v1beta1/traitdefinition/validating_handler.go:131:53: unused-parameter: parameter 'args' seems to be unused, consider removing or renaming it as _ (revive)
func RegisterValidatingHandler(mgr manager.Manager, args controller.Args) {
                                                    ^
pkg/webhook/core.oam.dev/v1beta1/traitdefinition/validating_handler.go:153:2: redefines-builtin-id: redefinition of the built-in function cap (revive)
	cap, err := appfile.ConvertTemplateJSON2Object(td.Name, td.Spec.Extension, td.Spec.Schematic)
	^
pkg/utils/parse.go:106:32: string `invalid format ` has 5 occurrences, make it a constant (goconst)
				return "", nil, errors.New("invalid format " + addr)
				                           ^
pkg/utils/k8s.go:402:10: superfluous-else: if block ends with a continue statement, so drop this else and outdent its block (revive)
		} else {
			return false
		}
pkg/workflow/providers/time/date.go:36:30: unused-parameter: parameter 'ctx' seems to be unused, consider removing or renaming it as _ (revive)
func (h *provider) Timestamp(ctx monitorContext.Context, wfCtx wfContext.Context, v *value.Value, act types.Action) error {
                             ^
pkg/workflow/providers/time/date.go:55:25: unused-parameter: parameter 'ctx' seems to be unused, consider removing or renaming it as _ (revive)
func (h *provider) Date(ctx monitorContext.Context, wfCtx wfContext.Context, v *value.Value, act types.Action) error {
                        ^
references/cli/top/config/color.go:34:6: `ThemeConfig` should be annotated with the `yaml` tag as it is passed to `yaml.v3.Unmarshal` at references/cli/top/config/color.go:130:9 (musttag)
type ThemeConfig struct {
     ^
pkg/oam/mock/mocks.go:56:6: `WorkloadReferencer` should be annotated with the `json` tag as it is passed to `json.Marshal` at pkg/oam/mock/mocks.go:106:12 (musttag)
type WorkloadReferencer struct{ Ref corev1.ObjectReference }
     ^
pkg/oam/mock/mocks.go:47:6: `ManagedResourceReferencer` should be annotated with the `json` tag as it is passed to `json.Marshal` at pkg/oam/mock/mocks.go:233:12 (musttag)
type ManagedResourceReferencer struct{ Ref *corev1.ObjectReference }
     ^
pkg/workflow/providers/multicluster/multicluster.go:53:71: unused-parameter: parameter 'wfCtx' seems to be unused, consider removing or renaming it as _ (revive)
func (p *provider) MakePlacementDecisions(ctx monitorContext.Context, wfCtx wfContext.Context, v *value.Value, act wfTypes.Action) error {
                                                                      ^
pkg/workflow/providers/multicluster/multicluster.go:111:37: unused-parameter: parameter 'ctx' seems to be unused, consider removing or renaming it as _ (revive)
func (p *provider) PatchApplication(ctx monitorContext.Context, wfCtx wfContext.Context, v *value.Value, act wfTypes.Action) error {
                                    ^
pkg/workflow/providers/multicluster/multicluster.go:141:61: unused-parameter: parameter 'wfCtx' seems to be unused, consider removing or renaming it as _ (revive)
func (p *provider) ListClusters(ctx monitorContext.Context, wfCtx wfContext.Context, v *value.Value, act wfTypes.Action) error {
                                                            ^
pkg/workflow/providers/multicluster/multicluster.go:172:82: unused-parameter: parameter 'wfCtx' seems to be unused, consider removing or renaming it as _ (revive)
func (p *provider) GetPlacementsFromTopologyPolicies(ctx monitorContext.Context, wfCtx wfContext.Context, v *value.Value, act wfTypes.Action) error {
                                                                                 ^
references/cli/def.go:691:57: string `.cue` has 6 occurrences, make it a constant (goconst)
			tempFilePath := filepath.Join(os.TempDir(), filename+".cue")
			                                                     ^
references/cli/dryrun.go:241:18: string `.yaml` has 5 occurrences, make it a constant (goconst)
		if fileType != ".yaml" && fileType != ".yml" && fileType != ".cue" {
		               ^
references/cli/workflow.go:75:32: unused-parameter: parameter 'c' seems to be unused, consider removing or renaming it as _ (revive)
func NewWorkflowSuspendCommand(c common.Args, ioStream cmdutil.IOStreams, wargs *WorkflowArgs) *cobra.Command {
                               ^
references/cli/top.go:35:49: unused-parameter: parameter 'ioStreams' seems to be unused, consider removing or renaming it as _ (revive)
func NewTopCommand(c common.Args, order string, ioStreams cmdutil.IOStreams) *cobra.Command {
                                                ^
references/cli/def.go:169:31: unused-parameter: parameter 'c' seems to be unused, consider removing or renaming it as _ (revive)
func NewDefinitionInitCommand(c common.Args) *cobra.Command {
                              ^
references/cli/addon.go:235:68: unused-parameter: parameter 'k8sClient' seems to be unused, consider removing or renaming it as _ (revive)
func AdditionalEndpointPrinter(ctx context.Context, c common.Args, k8sClient client.Client, name, info string, isUpgrade bool) {
                                                                   ^
references/cli/addon-registry.go:69:48: unused-parameter: parameter 'ioStreams' seems to be unused, consider removing or renaming it as _ (revive)
func NewAddAddonRegistryCommand(c common.Args, ioStreams cmdutil.IOStreams) *cobra.Command {
                                               ^
references/cli/addon-registry.go:106:48: unused-parameter: parameter 'ioStreams' seems to be unused, consider removing or renaming it as _ (revive)
func NewGetAddonRegistryCommand(c common.Args, ioStreams cmdutil.IOStreams) *cobra.Command {
                                               ^
references/cli/workflow.go:100:31: unused-parameter: parameter 'c' seems to be unused, consider removing or renaming it as _ (revive)
func NewWorkflowResumeCommand(c common.Args, ioStream cmdutil.IOStreams, wargs *WorkflowArgs) *cobra.Command {
                              ^
references/cli/addon-registry.go:127:49: unused-parameter: parameter 'ioStreams' seems to be unused, consider removing or renaming it as _ (revive)
func NewListAddonRegistryCommand(c common.Args, ioStreams cmdutil.IOStreams) *cobra.Command {
                                                ^
references/cli/addon.go:364:44: unused-parameter: parameter 'ioStream' seems to be unused, consider removing or renaming it as _ (revive)
func NewAddonDisableCommand(c common.Args, ioStream cmdutil.IOStreams) *cobra.Command {
                                           ^
references/cli/addon-registry.go:143:51: unused-parameter: parameter 'ioStreams' seems to be unused, consider removing or renaming it as _ (revive)
func NewUpdateAddonRegistryCommand(c common.Args, ioStreams cmdutil.IOStreams) *cobra.Command {
                                                  ^
references/cli/addon.go:1183:29: unused-parameter: parameter 'c' seems to be unused, consider removing or renaming it as _ (revive)
func NewAddonPackageCommand(c common.Args) *cobra.Command {
                            ^
references/cli/addon-registry.go:165:51: unused-parameter: parameter 'ioStreams' seems to be unused, consider removing or renaming it as _ (revive)
func NewDeleteAddonRegistryCommand(c common.Args, ioStreams cmdutil.IOStreams) *cobra.Command {
                                                  ^
references/cli/workflow.go:125:34: unused-parameter: parameter 'c' seems to be unused, consider removing or renaming it as _ (revive)
func NewWorkflowTerminateCommand(c common.Args, ioStream cmdutil.IOStreams, wargs *WorkflowArgs) *cobra.Command {
                                 ^
references/cli/workflow.go:146:32: unused-parameter: parameter 'c' seems to be unused, consider removing or renaming it as _ (revive)
func NewWorkflowRestartCommand(c common.Args, ioStream cmdutil.IOStreams, wargs *WorkflowArgs) *cobra.Command {
                               ^
references/cli/workflow.go:170:33: unused-parameter: parameter 'c' seems to be unused, consider removing or renaming it as _ (revive)
func NewWorkflowRollbackCommand(c common.Args, ioStream cmdutil.IOStreams, wargs *WorkflowArgs) *cobra.Command {
                                ^
references/cli/workflow.go:252:72: unused-parameter: parameter 'wargs' seems to be unused, consider removing or renaming it as _ (revive)
func NewWorkflowListCommand(c common.Args, ioStream cmdutil.IOStreams, wargs *WorkflowArgs) *cobra.Command {
                                                                       ^
pkg/webhook/core.oam.dev/v1beta1/application/validation.go:36:46: unused-parameter: parameter 'ctx' seems to be unused, consider removing or renaming it as _ (revive)
func (h *ValidatingHandler) ValidateWorkflow(ctx context.Context, app *v1beta1.Application) field.ErrorList {
                                             ^
pkg/webhook/core.oam.dev/v1beta1/application/validation.go:120:73: unused-parameter: parameter 'oldApp' seems to be unused, consider removing or renaming it as _ (revive)
func (h *ValidatingHandler) ValidateUpdate(ctx context.Context, newApp, oldApp *v1beta1.Application) field.ErrorList {
                                                                        ^
pkg/webhook/core.oam.dev/v1beta1/application/mutating_handler.go:52:42: unused-parameter: parameter 'ctx' seems to be unused, consider removing or renaming it as _ (revive)
func (h *MutatingHandler) handleIdentity(ctx context.Context, req admission.Request, _ *v1beta1.Application, app *v1beta1.Application) (bool, error) {
                                         ^
pkg/webhook/core.oam.dev/v1beta1/application/mutating_handler.go:69:42: unused-parameter: parameter 'ctx' seems to be unused, consider removing or renaming it as _ (revive)
func (h *MutatingHandler) handleWorkflow(ctx context.Context, req admission.Request, _ *v1beta1.Application, app *v1beta1.Application) (modified bool, err error) {
                                         ^
pkg/webhook/core.oam.dev/v1beta1/application/mutating_handler.go:87:42: unused-parameter: parameter 'ctx' seems to be unused, consider removing or renaming it as _ (revive)
func (h *MutatingHandler) handleSharding(ctx context.Context, req admission.Request, oldApp *v1beta1.Application, newApp *v1beta1.Application) (bool, error) {
                                         ^
pkg/config/factory.go:615:82: unused-parameter: parameter 'ns' seems to be unused, consider removing or renaming it as _ (revive)
func (k *kubeConfigFactory) CreateOrUpdateConfig(ctx context.Context, i *Config, ns string) error {
                                                                                 ^
pkg/config/factory.go:199:6: `CreateDistributionSpec` should be annotated with the `json` tag as it is passed to `json.Marshal` at pkg/config/factory.go:810:18 (musttag)
type CreateDistributionSpec struct {
     ^
pkg/addon/addon.go:399:7: string `.cue` has 5 occurrences, make it a constant (goconst)
	case ".cue":
	     ^
pkg/addon/push.go:166:42: response body must be closed (bodyclose)
	resp, err := cmClient.UploadChartPackage(chartPackagePath, p.ForceUpload)
	                                        ^
pkg/addon/addon.go:585:101: non-wrapping format verb for fmt.Errorf. Use `%w` to format errors (errorlint)
	return nil, nil, fmt.Errorf("unmarshalling failed for both file and directory content: %s and %w", fileUnmarshalError, directoryUnmarshalError)
	                                                                                                   ^
pkg/policy/override.go:34:84: unused-parameter: parameter 'app' seems to be unused, consider removing or renaming it as _ (revive)
func ParseOverridePolicyRelatedDefinitions(ctx context.Context, cli client.Client, app *v1beta1.Application, policy v1beta1.AppPolicy) (compDefs []*v1beta1.ComponentDefinition, traitDefs []*v1beta1.TraitDefinition, err error) {
                                                                                   ^
references/cli/top/model/cluster.go:68:10: superfluous-else: if block ends with a continue statement, so drop this else and outdent its block (revive)
		} else {
			clusterInfo.alias = cluster.Spec.Alias
			clusterInfo.clusterType = string(cluster.Spec.CredentialType)
			clusterInfo.endpoint = cluster.Spec.Endpoint
			var labels []string
			for k, v := range cluster.Labels {
				if !strings.HasPrefix(k, config.MetaApiGroupName) {
					labels = append(labels, "[blue::]"+k+"="+"[green::]"+v)
				}
			}
			clusterInfo.labels = strings.Join(labels, ",")
		}
references/cli/top/model/resource.go:85:22: `sonLeafResource` - `res` is unused (unparam)
func sonLeafResource(res querytypes.AppliedResource, node *querytypes.ResourceTreeNode, kind string, apiVersion string) []unstructured.Unstructured {
                     ^
pkg/velaql/view.go:162:75: unused-parameter: parameter 'owner' seems to be unused, consider removing or renaming it as _ (revive)
func (handler *ViewHandler) dispatch(ctx context.Context, cluster string, owner string, manifests ...*unstructured.Unstructured) error {
                                                                          ^
pkg/velaql/context.go:63:38: unused-parameter: parameter 'paths' seems to be unused, consider removing or renaming it as _ (revive)
func (c ViewContext) GetMutableValue(paths ...string) string {
                                     ^
pkg/velaql/context.go:68:38: unused-parameter: parameter 'data' seems to be unused, consider removing or renaming it as _ (revive)
func (c ViewContext) SetMutableValue(data string, paths ...string) {
                                     ^
pkg/velaql/view.go:173:57: unused-parameter: parameter 'cluster' seems to be unused, consider removing or renaming it as _ (revive)
func (handler *ViewHandler) delete(ctx context.Context, cluster string, owner string, manifest *unstructured.Unstructured) error {
                                                        ^
references/common/application.go:301:22: `sonLeafResource` - `res` is unused (unparam)
func sonLeafResource(res querytypes.AppliedResource, node *querytypes.ResourceTreeNode, kind string, apiVersion string) []unstructured.Unstructured {
                     ^
references/cuegen/convert.go:34:3: naked return in func `convertDecls` with 47 lines of code (nakedret)
		return
		^
```

</details>

I have:

- [x] Read and followed KubeVela's [contribution process](https://github.com/kubevela/kubevela/blob/master/contribute/create-pull-request.md).
- [ ] [Related Docs](https://github.com/kubevela/kubevela.io) updated properly. In a new feature or configuration option, an update to the documentation is necessary. 
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### How has this code been tested

Execution of existing unit tests

### CODE REVIEW

**Review by wonderflow — APPROVED** [review]

**Review by FogDong — APPROVED** [review]

**Comment by FogDong** [comment]
@Somefive @chivalryq @barnettZQG

**Review by Somefive — APPROVED** [review]
lgtm
